# Generated by Django 3.2.3 on 2021-05-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefDev',
            fields=[
                ('iddev', models.IntegerField(db_column='idDev', primary_key=True, serialize=False)),
                ('idrefs', models.IntegerField(db_column='idRefs')),
            ],
            options={
                'db_table': 'ref_dev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refs',
            fields=[
                ('idrefs', models.IntegerField(db_column='idRefs', primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, db_column='Owner_name', max_length=45, null=True)),
                ('owner_family', models.CharField(blank=True, db_column='Owner_family', max_length=45, null=True)),
                ('ref_name', models.CharField(blank=True, db_column='Ref_name', max_length=45, null=True)),
                ('owner_number', models.CharField(blank=True, db_column='Owner_number', max_length=45, null=True)),
                ('institute_name', models.CharField(blank=True, db_column='Institute_name', max_length=45, null=True)),
                ('deparmant_name', models.CharField(blank=True, db_column='Deparmant_name', max_length=45, null=True)),
            ],
            options={
                'db_table': 'refs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('idsms', models.IntegerField(db_column='idSms', primary_key=True, serialize=False)),
                ('textsms', models.CharField(blank=True, db_column='textSms', max_length=250, null=True)),
            ],
            options={
                'db_table': 'sms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.ForeignKey(db_column='idUsers', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersRef',
            fields=[
                ('idusers', models.IntegerField(db_column='idUsers', primary_key=True, serialize=False)),
                ('idrefs', models.IntegerField(db_column='idRefs')),
            ],
            options={
                'db_table': 'users_ref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('iddevices', models.OneToOneField(db_column='idDevices', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posts.refs')),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=45, null=True)),
                ('buildnumber', models.CharField(blank=True, db_column='BuildNumber', max_length=45, null=True)),
                ('idrefs_fk', models.IntegerField(blank=True, db_column='idRefs_Fk', null=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lastupdate',
            fields=[
                ('lasttime', models.IntegerField(blank=True, db_column='LastTime', null=True)),
                ('t_one', models.CharField(blank=True, db_column='T_one', max_length=45, null=True)),
                ('t_two', models.CharField(blank=True, db_column='T_two', max_length=45, null=True)),
                ('c_one', models.CharField(blank=True, db_column='C_one', max_length=45, null=True)),
                ('c_two', models.CharField(blank=True, db_column='C_two', max_length=45, null=True)),
                ('iddevices_fk', models.OneToOneField(db_column='idDevices_Fk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='posts.devices')),
            ],
            options={
                'db_table': 'lastupdate',
                'managed': False,
            },
        ),
    ]
